### PR TITLE
Abstraction and Documentation

### PR DESCRIPTION
**Pull request by cihangir**
This is the initial commit, AbstractOAuth2Client class must be splitted into two seperate classes, one for baseClient and one for OAuth stuff

### CODE REVIEW

**Comment by cihangir** [comment]
For https://github.com/silvester/ReverseOAuth2/pull/4#commitcomment-2120344

Hahaa, this was a reminder :) Lets map returning data to an entity class, and lets put this entity to session. This will lead to an abstraction between other providers

**Comment by cihangir** [comment]
For https://github.com/silvester/ReverseOAuth2/pull/4#commitcomment-2120354

First of all your are not using PHP in strict mode and this is not a good practise in development environment. You are trying to access variables that are not set.

For now, it is safe in module to regenerate, because you have coded in this way(accessed state directly from session, not used getState()) But in the future of course we must return null when there is no state

**Comment by silvester** [comment]
I can't merge all of your commit right now. The breaking point is returning a string from getInfo function, I use it as it is right now. All the other changes are welcome, so if you can roll back the change you have made in getInfo.

I also think that returning an entity from getInfo should not be the concern of the client. I think this should be done in Zend\Authenticate, because this is the place where you really authenticate the user. getInfo only assures that the user is the user he tells. But I am open to debate.

Thanks for your help.

Lp. Silvester

**Comment by cihangir** [comment]
For now, i am closing this pr, after completing little things on my side, we can debate on architecture. Sorry for late answer.

**Pull request closed without merging**
